version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    restart: unless-stopped
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $PWD/es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - $PWD/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  jenkins-master:
    build:
      context: ./jenkins
      args:
        JAVA_OPTS: '-Djenkins.CLI.disabled=true'
    restart: unless-stopped
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf/jenkins.yaml    
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - $PWD/jenkins/home:/var/jenkins_home
      - $PWD/jenkins/jenkins.yaml:/var/jenkins_conf/jenkins.yaml
