jenkins:
  systemMessage: "This Jenkins Master are configured automatically by the Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master"
  noUsageStatistics: true

  slaveAgentPort: 50000

  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin1234

  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:anonymous"
        - "Overall/Administer:authenticated"

jobs:
  - file: /var/jenkins_home/groovy/jobs/test-logstash-pipeline.groovy

unclassified:
  logstashconfiguration:
    enabled: true
    logstashIndexer: "elasticSearch"
